reset to upstream/c7-aarch64

diff --git a/SOURCES/Makefile.config b/SOURCES/Makefile.config
--- a/SOURCES/Makefile.config
+++ b/SOURCES/Makefile.config
@@ -2,128 +2,78 @@
 #
 # $Id$
 
+OUTPUT := $(abspath ../../)
+ifeq ("$(origin O)", "command line")
+  _EXTRA_ARGS := O=$(O)
+  OUTPUT := $(O)
+endif
+
 CFG		= kernel-$(VERSION)
+CFG_DIR		= $(OUTPUT)/configs
 
 CONFIGFILES	= \
-	$(CFG)-i686.config $(CFG)-i686-debug.config \
-	$(CFG)-i686-PAE.config $(CFG)-i686-PAEdebug.config \
-	$(CFG)-x86_64.config $(CFG)-x86_64-debug.config \
-	$(CFG)-s390x.config \
-	$(CFG)-armv7hl.config $(CFG)-armv7hl-lpae.config \
-	$(CFG)-aarch64.config \
-	$(CFG)-ppc64.config $(CFG)-ppc64p7.config $(CFG)-ppc64-debug.config \
-	$(CFG)-ppc64le.config $(CFG)-ppc64le-debug.config
+	$(CFG)-aarch64.config  $(CFG)-aarch64-debug.config
 
-PLATFORMS	= x86 x86_64 powerpc s390x arm arm64
+PLATFORMS	= arm64
 TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))
 
-configs: $(CONFIGFILES)
+configs: clean-configs $(CONFIGFILES)
 	@rm -f kernel-*-config
 	@rm -f $(TEMPFILES)
 	@rm -f temp-generic temp-*-generic temp-*-generic-tmp
 
+# Clean up our cruft so old merge files aren't used
+clean-configs:
+	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-arm64* kernel-*config config-*-merged
+
 # Augment the clean target to clean up our own cruft
 clean ::
-	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config
+	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-arm64* kernel-*config config-*-merged
 
-temp-generic: config-generic config-nodebug
+configs-prep: clean configs
+	@rm -fr $(CFG_DIR)
+	@mkdir -p $(CFG_DIR)
+	@cp $(CFG)*.config $(CFG_DIR)
+	@cd ../../ && \
+	for i in $(CFG_DIR)/*.config; do \
+		mv $$i $(OUTPUT)/.config; \
+		ARCH=$$(head -1 $(OUTPUT)/.config | cut -b 3-); \
+		echo "Configuring $$i"; \
+		make ARCH=$$ARCH listnewconfig $(_EXTRA_ARGS) >/dev/null || exit 1; \
+		make ARCH=$$ARCH oldnoconfig $(_EXTRA_ARGS) >/dev/null || exit 1; \
+		echo "# $$ARCH" > $$i; \
+		cat $(OUTPUT)/.config >> $$i; \
+		rm $(OUTPUT)/.config; \
+	done
+
+config-%-merged:
+	@if [ -f $$(basename $@ -merged)-redhat ]; then \
+		perl merge.pl $$(basename $@ -merged)-redhat $$(basename $@ -merged) >$@; \
+	else \
+		cp $$(basename $@ -merged) $@; \
+	fi
+
+temp-generic: config-nodebug-merged config-generic-merged
 	cat $^ > temp-generic
 
-temp-debug-generic: config-generic config-debug
+temp-debug-generic: config-debug-merged config-generic-merged
 	cat $^ > temp-debug-generic
 
-temp-no-extra-generic: config-no-extra temp-generic
+temp-arm-generic: config-arm-generic-merged temp-generic
 	perl merge.pl $^ > $@
 
-temp-arm-generic: config-arm-generic temp-no-extra-generic
+temp-arm-debug-generic: config-arm-generic-merged temp-debug-generic
 	perl merge.pl $^ > $@
 
-temp-armv7-generic: config-armv7-generic temp-arm-generic
+temp-arm64: config-arm64-merged temp-arm-generic
 	perl merge.pl $^ > $@
 
-temp-armv7: config-armv7 temp-armv7-generic
+temp-arm64-debug: config-arm64-merged temp-arm-debug-generic
 	perl merge.pl $^ > $@
-
-temp-armv7-lpae: config-armv7-lpae temp-armv7-generic
-	perl merge.pl $^ > $@
-
-temp-arm-debug-generic: temp-arm-generic temp-debug-generic
-	perl merge.pl $^ > $@
-
-temp-arm64: config-arm64 temp-arm-generic
-	perl merge.pl $^ > $@
-
-temp-arm64-debug: config-arm64 temp-arm-debug-generic
-	perl merge.pl $^ > $@
-
-temp-x86-32: config-x86-32-generic config-x86-generic
-	perl merge.pl $^  > $@
-
-temp-x86-32-generic: temp-x86-32 temp-generic
-	perl merge.pl $^  > $@
-
-temp-x86-debug-generic: temp-x86-32 temp-debug-generic
-	perl merge.pl $^  > $@
-
-temp-x86-64: config-x86_64-generic config-x86-generic
-	perl merge.pl $^  > $@
-
-temp-x86_64-generic: temp-x86-64 temp-generic
-	perl merge.pl $^  > $@
-
-temp-x86_64-debug-generic: temp-x86-64 temp-debug-generic
-	perl merge.pl $^  > $@
-
-temp-powerpc64-generic: config-powerpc64-generic temp-generic
-	perl merge.pl $^  > $@
-
-temp-powerpc64-debug-generic: config-powerpc64-generic temp-debug-generic
-	perl merge.pl $^  > $@
-
-temp-s390-generic: config-s390x temp-generic
-	perl merge.pl $^ > $@
-
-$(CFG)-i686-PAE.config: config-i686-PAE temp-x86-32-generic
-	perl merge.pl $^ i386 > $@
-
-$(CFG)-i686-PAEdebug.config: config-i686-PAE temp-x86-debug-generic
-	perl merge.pl $^ i386 > $@
-
-$(CFG)-i686.config: /dev/null temp-x86-32-generic
-	perl merge.pl $^ i386 > $@
-
-$(CFG)-i686-debug.config: /dev/null temp-x86-debug-generic
-	perl merge.pl $^ i386 > $@
-
-$(CFG)-x86_64.config: /dev/null temp-x86_64-generic
-	perl merge.pl $^ x86_64 > $@
-
-$(CFG)-x86_64-debug.config: /dev/null temp-x86_64-debug-generic
-	perl merge.pl $^ x86_64 > $@
-
-$(CFG)-ppc64.config: config-powerpc64 temp-powerpc64-generic
-	perl merge.pl $^ powerpc > $@
-
-$(CFG)-ppc64-debug.config: config-powerpc64 temp-powerpc64-debug-generic
-	perl merge.pl $^ powerpc > $@
-
-$(CFG)-ppc64p7.config: config-powerpc64p7 temp-powerpc64-generic
-	perl merge.pl $^ powerpc > $@
-
-$(CFG)-ppc64le.config: config-powerpc64le temp-powerpc64-generic
-	perl merge.pl $^ powerpc > $@
-
-$(CFG)-ppc64le-debug.config: config-powerpc64le temp-powerpc64-debug-generic
-	perl merge.pl $^ powerpc > $@
-
-$(CFG)-s390x.config: config-s390x temp-s390-generic
-	perl merge.pl $^ s390 > $@
-
-$(CFG)-armv7hl.config: /dev/null temp-armv7
-	perl merge.pl $^ arm > $@
-
-$(CFG)-armv7hl-lpae.config: /dev/null temp-armv7-lpae
-	perl merge.pl $^ arm > $@
 
 $(CFG)-aarch64.config: /dev/null temp-arm64
 	perl merge.pl $^ arm64 > $@
+
+$(CFG)-aarch64-debug.config: /dev/null temp-arm64-debug
+	perl merge.pl $^ arm64 > $@
+
